---
title: "Machine Learning"
format:
  html:
    sidebar: true
    grid:
      sidebar-width: 420px
---

<div id="tutor-root" data-chapter="11_machine_learning" class="tutor-floating"></div>
<script src="../assets/tutor-chat.js"></script>
<link rel="stylesheet" href="../assets/tutor-chat.css">


## Preparation for Class

- Watch the lecture recording

- Do any required reading (see below)

- Ask Dr. Lysenko any questions you have

- Pass Dr. Lysenko's quiz

## Lecture Recording and Slides

```{=html}
<div class="yt-embed">
  <div class="ratio">
    <iframe
      src="https://www.youtube.com/embed/dQw4w9WgXcQ"
      title="Lecture video"
      frameborder="0"
      allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"
      allowfullscreen>
    </iframe>
  </div>
</div>
```

```{=html}
<div style="width: 100%; height: 800px; margin-top: 1.5em;">
  <iframe
    src="../lecture_slides/11_machine_learning/11_machine_learning.pdf"
    style="width: 100%; height: 100%; border: 1px solid #ccc;"
    title="Lecture slides">
  </iframe>
</div>
```

## Required Reading

## Suggested Reading

[The Elements of Statistical Learning](https://hastie.su.domains/ElemStatLearn/)

## In-class Exercises

[Download the genotype data](../exercises/11_machine_learning/genotypes.csv)

[Download the intensity data](../exercises/11_machine_learning/intensities.RData)

[Download the other dataset for PCA](../exercises/11_machine_learning/pcadata.RData)


::: {.callout-tip collapse="true"}

### Exercise 1

`geno_data` (`genotypes.csv`) contains some genotyping array data.

- Check that you can understand what the variables (probably) mean

- What is n? What is p?

- Make some plots. What can you learn?

- What kind of structure do you think *could* exist in this dataset?

- Do any of the plots you made demonstrate that structure?

```{webr}
library("tidyverse")
# Read data
geno_data <- read.csv("https://jmc108.github.io/hugen2073-textbook/exercises/11_machine_learning/genotypes.csv")
# Peek at variables
geno_data[1:10,1:6]
# n and p
dim(geno_data)
# Scatterplot of 2 variables
geno_data %>% 
  ggplot()+
  geom_point(aes(x=rs1695824, y=rs13328662))
# Add some noise to clarify
geno_data %>% 
  ggplot()+
  geom_jitter(aes(x=rs1695824, y=rs13328662), width=0.05, height=0.05)
```

:::

::: {.callout-tip collapse="true"}

### Exercise 2

Try the same thing for another dataset, `X` (contained in `pcadata.Rdata`).

```{webr}
# Load data
load(url("https://jmc108.github.io/hugen2073-textbook/exercises/11_machine_learning/pcadata.RData"))
# Inspect
X[1:5,1:5]
dim(X)
# Scatterplot of two features
plot(X[,1],X[,300])
```


:::

::: {.callout-tip collapse="true"}

### "Exercise" 3 (curse of dimensionality)

In higher dimensions, points tend to become equidistant.

```{webr}
# 3a Distance concentration
# Draw 200 points from a normal distribution in d dimensions
# How close are the closest pair? How far are the furthest pair?
# Get the ratio of those distances (biggest to smallest)
set.seed(1)
distance_spread <- function(d, n=200) {
  X1 <- matrix(rnorm(n*d), nrow=n)
  D <- as.matrix(dist(X1))
  D <- D[upper.tri(D)]
  c(min=min(D), max=max(D), mean=mean(D))
}
# Do this in a bunch of dimensions from 2 to 10,000
dims <- c(2, 5, 10, 50, 100, 500, 1000, 10000)
results <- sapply(dims, distance_spread)
ratio <- results["min",] / results["max",]
plot(dims, ratio, type="b",
     xlab="Dimension",
     ylab="Min/max distance ratio",
     main="Distance concentration")
```

In higher dimensions, most of the volume is "near the boundary."

```{webr}
# 3b Volume explosion
# It's pretty obvious that measure increases exponentially with dimension
# But also see that most of the space is near the "boundary"
# (The unit ball is *inside* the unit cube in each space)
vol_ratio <- function(d) {
  (pi^(d/2) / gamma(d/2 + 1)) / (2^d)
}
dims <- 1:20
ratios <- sapply(dims, vol_ratio)
plot(dims, ratios, type="b",
     xlab="Dimension",
     ylab="Volume of unit ball / unit cube")
```

In higher dimensions, there is a lot of empty space.

```{webr}
# 3c Sparsity
# The average distance between uniform points gets bigger with dimension
dims <- 1:50
mean_dist <- sapply(dims, function(d) {
  X1 <- matrix(runif(1000*d), ncol=d)
  mean(dist(X1))
})
plot(dims, mean_dist, type="b",
     xlab="Dimension",
     ylab="Mean distance (uniform cube)")
```

In high-dimensional datasets, noise can look like structure.

```{webr}
# 3d "Hallucinating" structure
# Simulate random data
set.seed(1)
n <- 400
d <- 100
X1 <- matrix(rnorm(n*d), nrow=n)
# Apply fancy ML stuff!
# PCA for visualization
# K-means clustering in original high-D space
pca <- prcomp(X1, scale.=TRUE)
Z <- pca$x[,1:2]
# Plot the clusters
# Wow, we found patterns in the data! (But the data is random and meaningless)
km <- kmeans(X1, centers=4, nstart=50)
plot(Z, col=km$cluster, pch=16,
     xlab="PC1", ylab="PC2",
     main="Pure noise + k-means clustering")
# Draw convex hulls to exaggerate cluster appearance
for (k in 1:4) {
  pts <- Z[km$cluster == k, ]
  hull <- chull(pts)
  polygon(pts[hull, ], border=k, lwd=2)
}
```

:::

::: {.callout-tip collapse="true"}

### Exercise 4

Let's apply PCA to the two datasets from Exercises 1-2 (`X` and `pcadata`).

- Apply PCA to `X`

- Use the `prcomp` function

- Try a 2D plot of the PCs (use a small plotting symbol, like `pch="."`)

```{webr}
pca <- prcomp(X)
pc1 <- pca$x[,1]
pc2 <- pca$x[,2]
plot(pc1,pc2, pch=".")
```

- Now do the same for `geno_data`

- Are there any variables you should leave out?

- Make a 2D plot - how do you interpret it?

- Do you wonder anything about PC3? Plot it, too.

```{webr}
library("plotly")
library("scatterplot3d")
pca <- prcomp(geno_data[,c(-1,-2)])
pc1 <- pca$x[,1]
pc2 <- pca$x[,2]
plot(pc1,pc2, col=factor(geno_data$population))

pc3 <- pca$x[,3]
pcdata <- data.frame(pc1=pc1, pc2=pc2, pc3=pc3, group=geno_data$population)
plot_ly(pcdata,
        x = ~pc1,
        y = ~pc2,
        z = ~pc3,
        color = ~group,
        type = "scatter3d",
        mode = "markers")
scatterplot3d(pcdata$pc1,
              pcdata$pc2,
              pcdata$pc3,
              color=as.numeric(factor(pcdata$group)))
```
:::

::: {.callout-tip collapse="true"}

### Exercise 5

Make a scree plot to show the importance of the PCs. How many look "interesting"?

```{webr}
# Variance explained
var_explained <- pca$sdev^2
prop_var <- var_explained / sum(var_explained)
# Scree plot
par(mfrow=c(1,2))
plot(prop_var,
     xlab = "Principal Component",
     ylab = "Proportion of Variance Explained")
plot(prop_var,
     xlab = "Principal Component",
     ylab = "Proportion of Variance Explained",
     xlim=c(1,20))
par(mfrow=c(1,1))
```


:::

::: {.callout-tip collapse="true"}

### Exercise 6

Make a parallel coordinate plot, colored by population

- How many PCs should you use for the plot?

- Tryo to interpret the plot

```{webr}
library("GGally")
p <- ggparcoord(
  cbind(
    pca$x[,1:20],
    data.frame(geno_data$population)
    ),
  columns = 1:20,
  groupColumn = 21) 
p$layers[[1]]$aes_params$linewidth <- 0.2
p
```


:::

::: {.callout-tip collapse="true"}

### Exercise 7

Repeat exercise 6 for only the HCB+JPT subset of the data. Include the scatterplot of the first 2 PCs and the scree plot(s).

```{webr}
pca2 <- prcomp(geno_data[geno_data$population %in% c("HCB","JPT"),c(-1,-2)])
pc1 <- pca2$x[,1]
pc2 <- pca2$x[,2]
plot(pc1,pc2, col=factor(geno_data$population[geno_data$population %in% c("HCB","JPT")]))
var_explained <- pca$sdev^2
prop_var <- var_explained / sum(var_explained)
plot(prop_var,
     xlab = "Principal Component",
     ylab = "Proportion of Variance Explained")
plot(prop_var,
     xlab = "Principal Component",
     ylab = "Proportion of Variance Explained",
     xlim=c(1,20))
```

:::

::: {.callout-tip collapse="true"}

### Exercise 8

Repeat exercise 6 for only the HCB+JPT subset of the data.

```{webr}
ggparcoord(
  cbind(
    pca2$x[,1:20],
    data.frame(geno_data$population[geno_data$population %in% c("HCB","JPT")])
  ),
  columns = 1:20,
  groupColumn = 21
) + labs(colour = "Population")
```


:::

::: {.callout-tip collapse="true"}

### Exercise 9

`xintensity` and `yintensity` contain genotyping array data, namely each sample's intensity for each probe.

First, let's look at scatterplots of the intensities for a few SNPs.

- How many clusters should we expect/use? Why?

- Pick a SNP (a plot number) that looks good (well-genotyped)

- Pick one that looks poorly genotyped

```{webr}
# Look at these SNP intensity plots from a genotyping array
# Imagine we want to call the genotypes by clustering the points
# First, how many clusters should we expect/use?
# Second, pick a SNP you think is well-genotped and a SNP you think is poorly genoyped
# We will try clustering them with k-means
load(url("https://jmc108.github.io/hugen2073-textbook/exercises/11_machine_learning/intensities.RData"))
par(mfrow=c(6,6), mar=c(1,1,1,1))
for (i in 1:36) {
  plot(xintensity[i,], yintensity[i,],
       main=i, cex=0.4,
       xlab="", ylab="",
       xaxt="n", yaxt="n")
}
par(mfrow=c(1,1))

```

Here's a function that will implement an interactive k-means algorithm to cluster the data. You don't need to change anything in this chunk. You'll run the `kmeans_click` function in the chunk after.

```{webr}
k <- 3
kmeans_click <- function(x, y, k = 3, iters = 20, seed = 1) {
  set.seed(seed)
  pts <- cbind(as.numeric(x), as.numeric(y))
  pts <- pts[complete.cases(pts), , drop = FALSE]
  n <- nrow(pts)
  
  cols <- c("red","blue","darkgreen","orange","purple","brown","cyan","magenta")[1:k]
  centers <- pts[sample.int(n, k), , drop = FALSE]
  
  # show initial random seeds
  plot(pts[,1], pts[,2], pch=16, col="grey70", xlab="X", ylab="Y",
       main="init seeds (click)")
  points(centers[,1], centers[,2], pch=4, cex=3, lwd=3, col=cols)
  locator(1)
  
  cl_old <- integer(n)
  
  for (t in 1:iters) {
    # assign
    d2 <- sapply(1:k, function(j)
      (pts[,1]-centers[j,1])^2 + (pts[,2]-centers[j,2])^2
    )
    cl <- max.col(-d2)
    
    # update (with empty-cluster reseed)
    for (j in 1:k) {
      idx <- which(cl == j)
      if (length(idx) > 0) centers[j,] <- colMeans(pts[idx, , drop=FALSE])
      else centers[j,] <- pts[sample.int(n, 1), ]
    }
    
    plot(pts[,1], pts[,2], pch=16, col=cols[cl], xlab="X", ylab="Y",
         main=paste("iter", t, "(click)"))
    points(centers[,1], centers[,2], pch=4, cex=3, lwd=3, col=cols)
    locator(1)
    
    if (identical(cl, cl_old)) break
    cl_old <- cl
  }
  
  invisible(list(cluster=cl, centers=centers))
}

```

Now run k-means for the two SNPs you picked. For each one, try several different values of `seed`.

```{webr}
# Succeeds?
i <- 4
x <-  xintensity[i,]
y <-  yintensity[i,]
kmeans_click(x, y, k = 3, seed = 4)

# Fails?
i <- 4
x <-  xintensity[i,]
y <-  yintensity[i,]
kmeans_click(x, y, k = 3, seed = 2)

# What do you think of these clusters?
i <- 33
x <-  xintensity[i,]
y <-  yintensity[i,]
kmeans_click(x, y, k = 3, seed = 4)
```


:::

::: {.callout-tip collapse="true"}

### Exercise 10

Now try interactively running k-means on the principal components of ancestry contained in `pca$x`. This chunk just sets up the function you'll use - don't change it.

```{webr}
kmeans_pca_step_s3d <- function(pcx,
                                k = 3, iters = 20, seed = 1,
                                use_pcs = NULL,          # which PCs to use for distance; NULL = all
                                plot_pcs = 1:3,          # which 3 PCs to plot
                                pause = TRUE,
                                pch = 16, cex = 0.4,
                                center_pch = 4, center_cex = 2.2, center_lwd = 3,
                                theta = 40, phi = 20, truth=NULL) {

  if (!requireNamespace("scatterplot3d", quietly = TRUE)) {
    stop("Install scatterplot3d: install.packages('scatterplot3d')")
  }

  pcx <- as.matrix(pcx)
  keep <- complete.cases(pcx)
  pcx <- pcx[keep, , drop = FALSE]
  if (!is.null(truth)) truth <- truth[keep]
  n <- nrow(pcx)
  
  if (is.null(truth)) {
  pch_vec <- pch
} else {
  # map each truth group to a plotting character
  tt <- as.factor(truth)
  pchs <- c(1:25)                    # available base pch values
  if (nlevels(tt) > length(pchs)) stop("Too many truth groups for available pch values.")
  pch_vec <- pchs[as.integer(tt)]
}
  
  p <- ncol(pcx)
  if (n < k) stop("Need at least k complete rows in pcx.")
  if (p < 3) stop("Need at least 3 PCs to plot.")

  if (is.null(use_pcs)) use_pcs <- seq_len(p)
  if (length(plot_pcs) != 3) stop("plot_pcs must be length 3 (e.g., 1:3).")

  use_pcs <- as.integer(use_pcs)
  plot_pcs <- as.integer(plot_pcs)

  # data for distance + for plotting
  pts_use  <- pcx[, use_pcs, drop = FALSE]
  pts_plot <- pcx[, plot_pcs, drop = FALSE]

  set.seed(seed)

  cols_all <- c("red","blue","darkgreen","orange","purple","brown","cyan","magenta")
  if (k > length(cols_all)) stop("k too large for built-in color list.")
  cols <- cols_all[1:k]

  # init centers in FULL (use_pcs) space
  centers_use <- pts_use[sample.int(n, k), , drop = FALSE]
  cl_old <- integer(n)

  draw <- function(point_cols, main_txt) {
    s3d <- scatterplot3d::scatterplot3d(
      x = pts_plot[,1], y = pts_plot[,2], z = pts_plot[,3],
      color = point_cols, pch = pch, cex.symbols = cex,
      xlab = paste0("PC", plot_pcs[1]),
      ylab = paste0("PC", plot_pcs[2]),
      zlab = paste0("PC", plot_pcs[3]),
      main = main_txt,
      angle = theta
    )

    # centers need to be shown in plot space too:
    # take their coordinates from centers_use but only those PCs that are plotted.
    # If plot_pcs is not a subset of use_pcs, we must map them via the original pcx columns.
    centers_plot <- matrix(NA_real_, nrow = k, ncol = 3)
    for (j in 1:k) {
      # center in full PC coordinates (all columns) isn't directly stored,
      # so reconstruct by averaging in original pcx columns for assigned members later.
      # During init, centers_use lives only in use_pcs; so we can still plot by
      # taking those dimensions if plot_pcs are included; otherwise plot after first assignment.
      centers_plot[j,] <- NA_real_
    }

    invisible(s3d)
  }

  # initial view: points only + seed markers if possible
  s3d <- scatterplot3d::scatterplot3d(
    x = pts_plot[,1], y = pts_plot[,2], z = pts_plot[,3],
    color = "grey70", pch = pch_vec, cex.symbols = cex,
    xlab = paste0("PC", plot_pcs[1]),
    ylab = paste0("PC", plot_pcs[2]),
    zlab = paste0("PC", plot_pcs[3]),
    main = "init seeds (press Enter)",
    angle = theta
  )

  # plot initial centers only if plot_pcs are included in use_pcs
  if (all(plot_pcs %in% use_pcs)) {
    # find which columns inside pts_use correspond to the plotted PCs
    idx_in_use <- match(plot_pcs, use_pcs)
    centers_plot <- centers_use[, idx_in_use, drop = FALSE]
    cc <- s3d$xyz.convert(centers_plot[,1], centers_plot[,2], centers_plot[,3])
    points(cc$x, cc$y, pch = center_pch, cex = center_cex, lwd = center_lwd, col = cols)
  }

  if (pause) readline("Enter to continue...")

  for (t in 1:iters) {
    # assign in FULL (use_pcs) space
    d2 <- sapply(1:k, function(j) {
      rowSums((pts_use - matrix(centers_use[j,], nrow = n, ncol = ncol(pts_use), byrow = TRUE))^2)
    })
    cl <- max.col(-d2)

    # update centers in FULL (use_pcs) space (with empty-cluster reseed)
    for (j in 1:k) {
      idx <- which(cl == j)
      if (length(idx) > 0) centers_use[j,] <- colMeans(pts_use[idx, , drop = FALSE])
      else centers_use[j,] <- pts_use[sample.int(n, 1), ]
    }

    # redraw in PLOT (3D) space
    s3d <- scatterplot3d::scatterplot3d(
      x = pts_plot[,1], y = pts_plot[,2], z = pts_plot[,3],
      color = cols[cl], pch = pch_vec, cex.symbols = cex,
      xlab = paste0("PC", plot_pcs[1]),
      ylab = paste0("PC", plot_pcs[2]),
      zlab = paste0("PC", plot_pcs[3]),
      main = paste("iter", t, "(distance uses PCs:", length(use_pcs), ")"),
      angle = theta
    )

    # project centers to plot space when possible
    if (all(plot_pcs %in% use_pcs)) {
      idx_in_use <- match(plot_pcs, use_pcs)
      centers_plot <- centers_use[, idx_in_use, drop = FALSE]
    } else {
      # If plotted PCs aren’t included in use_pcs, best fallback is to compute centers
      # in full original PC space from current assignments:
      centers_plot <- t(vapply(1:k, function(j) {
        idx <- which(cl == j)
        if (length(idx) > 0) colMeans(pcx[idx, plot_pcs, drop = FALSE]) else pcx[sample.int(n,1), plot_pcs]
      }, numeric(3)))
    }

    cc <- s3d$xyz.convert(centers_plot[,1], centers_plot[,2], centers_plot[,3])
    points(cc$x, cc$y, pch = center_pch, cex = center_cex, lwd = center_lwd, col = cols)

    if (pause) readline("Enter to continue...")

    if (identical(cl, cl_old)) break
    cl_old <- cl
  }

  invisible(list(cluster = cl_old, centers_use = centers_use,
                 use_pcs = use_pcs, plot_pcs = plot_pcs))
}

```

What should k be? We know there are 4 population groups here. How does the algorithm do at calling them?

Try different values of `seed` and `k`.

```{webr}
kmeans_pca_step_s3d(pca$x, k=4, truth = geno_data$population, seed=1)
kmeans_pca_step_s3d(pca$x, k=4, truth = geno_data$population, seed=2)
kmeans_pca_step_s3d(pca$x, k=4, truth = geno_data$population, seed=3)
kmeans_pca_step_s3d(pca$x, k=4, truth = geno_data$population, seed=4)
```


:::


::: {.callout-tip collapse="true"}

### Example 1

Here we apply logistic regression, ridge regression, LASSO, and elastic net to the Golub dataset to predict tumor type.

- The logistic regression may produce errors and need to be commented out

- We have arbitrarily chosen lambda=1 and have not split the data into training and testing sets.

```{webr}
#library(golubEsets)
library(glmnet)

load(url("https://jmc108.github.io/hugen2073-textbook/exercises/11_machine_learning/example1.RData"))


n <- nrow(X); p <- ncol(X)
cat("n =", n, "p =", p, "\n")

# Fixed lambda (for example)
lambda_val <- 0.1

# Fit models
# (A) Unpenalized logistic regression via glm()
# This might fail!
logit_fit <- tryCatch(
  glm(y_bin ~ ., data = data.frame(y_bin = y_bin, X), family = binomial),
  error = function(e) e
)

# (B) glmnet fits
ridge_fit <- glmnet(X, y_bin, family = "binomial", alpha = 0,   lambda = lambda_val)
lasso_fit <- glmnet(X, y_bin, family = "binomial", alpha = 1,   lambda = lambda_val)
en_fit    <- glmnet(X, y_bin, family = "binomial", alpha = 0.5, lambda = lambda_val)

# extract betas (exclude intercept)
get_beta_glmnet <- function(fit) {
  b <- as.vector(coef(fit))[-1]
  b
}

b_ridge <- get_beta_glmnet(ridge_fit)
b_lasso <- get_beta_glmnet(lasso_fit)
b_en    <- get_beta_glmnet(en_fit)

# logistic betas (if model fit succeeded)
b_logit <- rep(NA_real_, p)
logit_ok <- !inherits(logit_fit, "error")
if (logit_ok) {
  # coef(logit_fit) includes intercept then coefficients for columns (if estimable)
  # When p >> n, glm may drop/alias predictors; we align by column names if possible.
  # Column names in data.frame(y_bin, X) are "y_bin" then colnames(X)
  cf <- coef(logit_fit)
  cf <- cf[names(cf) != "(Intercept)"]
  b_logit <- rep(0, p)
  names(b_logit) <- colnames(X)
  overlap <- intersect(names(b_logit), names(cf))
  b_logit[overlap] <- cf[overlap]
} else {
  message("Unpenalized logistic failed to fit (expected in p >> n).")
}

# 2. Plot: # nonzero coefficients (sparsity)

nnz <- function(b, tol = 1e-10) sum(abs(b) > tol)

nz_counts <- c(
  Logistic = if (logit_ok) nnz(b_logit) else NA_real_,
  Ridge    = nnz(b_ridge),
  Lasso    = nnz(b_lasso),
  EN       = nnz(b_en)
)

par(mfrow = c(1,1))
barplot(nz_counts,
        main = paste0("Sparsity at lambda = ", lambda_val),
        ylab = "# nonzero coefficients (genes)",
        las = 1)

# 3. Plot: distribution of |beta|
#    (ridge vs lasso vs EN; logistic optional)

abs_list <- list(
  Ridge = abs(b_ridge),
  Lasso = abs(b_lasso),
  EN    = abs(b_en)
)

# Optionally add logistic if it fit and is meaningful
if (logit_ok) abs_list$Logistic <- abs(b_logit)

# Use a common x-range (drop infinities / NAs)
all_abs <- unlist(abs_list)
all_abs <- all_abs[is.finite(all_abs)]
xmax <- quantile(all_abs, 0.99, na.rm = TRUE)

# density plots (excluding exact zeros helps show shapes; we'll include a zero-spike separately)
dens <- lapply(abs_list, function(v) density(v[v > 0 & is.finite(v)], na.rm = TRUE))

plot(dens[[1]],
     main = "|β| distributions (excluding exact zeros)",
     xlab = "|β|", xlim = c(0, xmax))
if (length(dens) > 1) {
  for (k in 2:length(dens)) lines(dens[[k]])
}
legend("topright", legend = names(dens), lwd = 1, bty = "n")

# Show the zero-mass explicitly (a simple barplot)
zero_frac <- sapply(abs_list, function(v) mean(abs(v) <= 1e-10, na.rm = TRUE))
barplot(zero_frac,
        main = "Fraction of coefficients exactly 0",
        ylab = "fraction",
        las = 1)


# Training Accuracy for All Models

get_train_acc_glmnet <- function(fit, X, y) {
  prob <- as.vector(predict(fit, X, type = "response"))
  pred <- ifelse(prob > 0.5, 1, 0)
  mean(pred == y)
}

# Logistic regression accuracy
if (logit_ok) {
  logit_prob <- predict(logit_fit, type = "response")
  logit_pred <- ifelse(logit_prob > 0.5, 1, 0)
  acc_logit  <- mean(logit_pred == y_bin)
} else {
  acc_logit <- NA
}

# Ridge / Lasso / EN accuracy
acc_ridge <- get_train_acc_glmnet(ridge_fit, X, y_bin)
acc_lasso <- get_train_acc_glmnet(lasso_fit, X, y_bin)
acc_en    <- get_train_acc_glmnet(en_fit, X, y_bin)

# Collect
acc_vec <- c(
  Logistic = acc_logit,
  Ridge    = acc_ridge,
  Lasso    = acc_lasso,
  EN       = acc_en
)

print(acc_vec)

# Bar plot
barplot(acc_vec,
        main = "Training Accuracy (No Train/Test Split)",
        ylab = "Accuracy",
        ylim = c(0, 1),
        las = 1)

```


::: 

::: {.callout-tip collapse="true"}

### Example 2

Here we repeat Example 1, but now we apply cross validation on a training set and estimate accuracy on a testing set.

```{webr}
#library(golubEsets)
library(glmnet)
library(pROC)

load(url("https://jmc108.github.io/hugen2073-textbook/exercises/11_machine_learning/example2.RData"))



# 0.  Train/Test split
set.seed(1)
train_frac <- 0.7
train_idx <- sample(seq_len(n), size = floor(train_frac * n))
test_idx  <- setdiff(seq_len(n), train_idx)

X_train <- X[train_idx, , drop = FALSE]
X_test  <- X[test_idx,  , drop = FALSE]
y_train <- y_bin[train_idx]
y_test  <- y_bin[test_idx]

cat("Train n =", nrow(X_train), " Test n =", nrow(X_test), "\n")

# 1. Fit models (CV on TRAIN only for ridge/lasso/EN)

# (A) Unpenalized logistic regression via glm() on TRAIN
# (expected to be unstable when p >> n)
logit_fit <- tryCatch(
  glm(y_train ~ ., data = data.frame(y_train = y_train, X_train), family = binomial),
  error = function(e) e
)
logit_ok <- !inherits(logit_fit, "error")

# (B) CV fits for ridge/lasso/EN (choose lambda on TRAIN only)
k_folds <- 10
type_measure <- "deviance"  # for binomial

set.seed(1)
cv_ridge <- cv.glmnet(X_train, y_train, family = "binomial", alpha = 0,
                      nfolds = k_folds, type.measure = type_measure)

set.seed(1)
cv_lasso <- cv.glmnet(X_train, y_train, family = "binomial", alpha = 1,
                      nfolds = k_folds, type.measure = type_measure)

alpha_en <- 0.5
set.seed(1)
cv_en <- cv.glmnet(X_train, y_train, family = "binomial", alpha = alpha_en,
                   nfolds = k_folds, type.measure = type_measure)

# Choose lambda rule (min vs 1se)
use_1se <- FALSE
pick_lambda <- function(cvobj) if (use_1se) cvobj$lambda.1se else cvobj$lambda.min

lam_ridge <- pick_lambda(cv_ridge)
lam_lasso <- pick_lambda(cv_lasso)
lam_en    <- pick_lambda(cv_en)

cat("\nChosen lambdas (", if (use_1se) "lambda.1se" else "lambda.min", "):\n", sep = "")
print(data.frame(
  Model = c("Ridge", "Lasso", paste0("EN (alpha=", alpha_en, ")")),
  lambda = c(lam_ridge, lam_lasso, lam_en)
))

# Fit final penalized models on TRAIN at chosen lambda
ridge_fit <- glmnet(X_train, y_train, family = "binomial", alpha = 0,   lambda = lam_ridge)
lasso_fit <- glmnet(X_train, y_train, family = "binomial", alpha = 1,   lambda = lam_lasso)
en_fit    <- glmnet(X_train, y_train, family = "binomial", alpha = alpha_en, lambda = lam_en)

# helpers
get_beta_glmnet <- function(fit) as.vector(coef(fit))[-1]  # exclude intercept
nnz <- function(b, tol = 1e-10) sum(abs(b) > tol)

# For logistic glm() coefficients (align to gene columns)
get_beta_logit_aligned <- function(fit, p, colnamesX) {
  b <- rep(0, p); names(b) <- colnamesX
  cf <- coef(fit)
  cf <- cf[names(cf) != "(Intercept)"]
  overlap <- intersect(names(b), names(cf))
  b[overlap] <- cf[overlap]
  b
}

# Accuracy/AUC from predicted probabilities
metrics_from_prob <- function(prob, y_true) {
  pred <- ifelse(prob > 0.5, 1, 0)
  acc <- mean(pred == y_true)
  aucv <- as.numeric(pROC::auc(y_true, prob))
  list(acc = acc, auc = aucv, pred = pred)
}

# Confusion matrix (counts)
conf_mat <- function(y_true, y_pred) {
  # rows=true, cols=pred; order 0 then 1
  tab <- table(factor(y_true, levels = c(0,1)),
               factor(y_pred, levels = c(0,1)))
  dimnames(tab) <- list(True = c("0","1"), Pred = c("0","1"))
  tab
}

# Heatmap-ish plot for confusion matrix
plot_confmat <- function(cm, main = "Confusion matrix") {
  m <- as.matrix(cm)
  # image() needs numeric matrix; flip vertically for nicer orientation
  image(t(m[nrow(m):1, , drop=FALSE]),
        axes = FALSE, main = main)
  axis(1, at = seq(0,1,length.out=ncol(m)), labels = colnames(m))
  axis(2, at = seq(0,1,length.out=nrow(m)), labels = rev(rownames(m)))
  # overlay counts
  for (i in 1:nrow(m)) for (j in 1:ncol(m)) {
    # map (i,j) to image coordinates: j along x, reversed i along y
    x <- (j-1)/(ncol(m)-1)
    y <- (nrow(m)-i)/(nrow(m)-1)
    text(x, y, labels = m[i,j])
  }
  box()
}

# 2. CV curve plots (TRAIN CV only) with best lambdas marked
par(mfrow = c(1,3))

plot(cv_ridge, main = paste0("Ridge CV (k=", k_folds, ", train only)"))
abline(v = log(cv_ridge$lambda.min), lty = 2)
abline(v = log(cv_ridge$lambda.1se), lty = 3)
legend("topright", legend = c("lambda.min", "lambda.1se"), lty = c(2,3), bty="n")

plot(cv_lasso, main = paste0("Lasso CV (k=", k_folds, ", train only)"))
abline(v = log(cv_lasso$lambda.min), lty = 2)
abline(v = log(cv_lasso$lambda.1se), lty = 3)
legend("topright", legend = c("lambda.min", "lambda.1se"), lty = c(2,3), bty="n")

plot(cv_en, main = paste0("EN CV (alpha=", alpha_en, ", train only)"))
abline(v = log(cv_en$lambda.min), lty = 2)
abline(v = log(cv_en$lambda.1se), lty = 3)
legend("topright", legend = c("lambda.min", "lambda.1se"), lty = c(2,3), bty="n")

par(mfrow = c(1,1))

# 3. Betas at chosen lambda (penalized models) + logistic (train)
b_ridge <- get_beta_glmnet(ridge_fit)
b_lasso <- get_beta_glmnet(lasso_fit)
b_en    <- get_beta_glmnet(en_fit)

b_logit <- rep(NA_real_, p)
if (logit_ok) b_logit <- get_beta_logit_aligned(logit_fit, p, colnames(X_train))

# 4. Sparsity plot (# nonzero)
nz_counts <- c(
  Logistic = if (logit_ok) nnz(b_logit) else NA_real_,
  Ridge    = nnz(b_ridge),
  Lasso    = nnz(b_lasso),
  EN       = nnz(b_en)
)

barplot(nz_counts,
        main = paste0("Sparsity at CV-chosen lambda (", if (use_1se) "1se" else "min", ")"),
        ylab = "# nonzero coefficients (genes)",
        las = 1)

# 5. |beta| distributions + fraction exactly zero
abs_list <- list(
  Ridge = abs(b_ridge),
  Lasso = abs(b_lasso),
  EN    = abs(b_en)
)
if (logit_ok) abs_list$Logistic <- abs(b_logit)

all_abs <- unlist(abs_list)
all_abs <- all_abs[is.finite(all_abs)]
xmax <- quantile(all_abs, 0.99, na.rm = TRUE)

dens <- lapply(abs_list, function(v) {
  v_clean <- v[v > 0 & is.finite(v)]
  if (length(v_clean) > 1) {
    density(v_clean)
  } else {
    NULL
  }
})
dens_nonnull <- dens[!sapply(dens, is.null)]


if (length(dens_nonnull) > 0) {
  plot(dens_nonnull[[1]],
       main = "|β| distributions (excluding exact zeros)",
       xlab = "|β|")
  
  if (length(dens_nonnull) > 1) {
    for (k in 2:length(dens_nonnull)) {
      lines(dens_nonnull[[k]])
    }
  }
  
  legend("topright",
         legend = names(dens_nonnull),
         lwd = 1,
         bty = "n")
} else {
  plot.new()
  title("No nonzero coefficients to plot")
}
zero_frac <- sapply(abs_list, function(v) mean(abs(v) <= 1e-10, na.rm = TRUE))
barplot(zero_frac,
        main = "Fraction of coefficients exactly 0",
        ylab = "fraction",
        las = 1)



# 7. Coefficient path plots (from TRAIN fits used by CV)
ridge_path <- cv_ridge$glmnet.fit
lasso_path <- cv_lasso$glmnet.fit
en_path    <- cv_en$glmnet.fit

par(mfrow = c(1,3))
plot(ridge_path, xvar = "lambda", main = "Ridge coefficient paths")
plot(lasso_path, xvar = "lambda", main = "Lasso coefficient paths")
plot(en_path,    xvar = "lambda", main = paste0("EN paths (alpha=", alpha_en, ")"))
par(mfrow = c(1,1))

# 8. FINAL HOLDOUT TEST PERFORMANCE (Accuracy + AUC + Confusion Matrices)

# Predict probabilities on TEST
# Penalized models
prob_ridge <- as.vector(predict(ridge_fit, X_test, type = "response"))
prob_lasso <- as.vector(predict(lasso_fit, X_test, type = "response"))
prob_en    <- as.vector(predict(en_fit,    X_test, type = "response"))

# Unpenalized logistic (if fit succeeded)
if (logit_ok) {
  # predict() for glm uses same feature columns it was trained with
  prob_logit <- tryCatch(
    as.vector(predict(logit_fit, newdata = data.frame(X_train = X_test), type = "response")),
    error = function(e) rep(NA_real_, length(y_test))
  )
} else {
  prob_logit <- rep(NA_real_, length(y_test))
}

# Compute metrics
m_ridge <- metrics_from_prob(prob_ridge, y_test)
m_lasso <- metrics_from_prob(prob_lasso, y_test)
m_en    <- metrics_from_prob(prob_en,    y_test)

if (all(is.finite(prob_logit))) {
  m_logit <- metrics_from_prob(prob_logit, y_test)
} else {
  m_logit <- list(acc = NA_real_, auc = NA_real_, pred = rep(NA_integer_, length(y_test)))
}

acc_vec_test <- c(
  Logistic = m_logit$acc,
  Ridge    = m_ridge$acc,
  Lasso    = m_lasso$acc,
  EN       = m_en$acc
)
auc_vec_test <- c(
  Logistic = m_logit$auc,
  Ridge    = m_ridge$auc,
  Lasso    = m_lasso$auc,
  EN       = m_en$auc
)

print(data.frame(Model = names(acc_vec_test),
                 Test_Accuracy = acc_vec_test,
                 Test_AUC = auc_vec_test))

par(mfrow = c(1,2))
barplot(acc_vec_test,
        main = "Holdout Test Accuracy",
        ylab = "Accuracy", ylim = c(0,1), las = 1)

barplot(auc_vec_test,
        main = "Holdout Test AUC",
        ylab = "AUC", ylim = c(0,1), las = 1)
par(mfrow = c(1,1))

# Confusion matrices (TEST)
cm_logit <- if (logit_ok && all(is.finite(prob_logit))) conf_mat(y_test, m_logit$pred) else NA
cm_ridge <- conf_mat(y_test, m_ridge$pred)
cm_lasso <- conf_mat(y_test, m_lasso$pred)
cm_en    <- conf_mat(y_test, m_en$pred)

par(mfrow = c(2,2))
if (is.matrix(cm_logit) || is.table(cm_logit)) {
  plot_confmat(cm_logit, main = "Logistic (test)")
} else {
  plot.new(); title("Logistic (test)\nfit failed / NA")
}
plot_confmat(cm_ridge, main = "Ridge (test)")
plot_confmat(cm_lasso, main = "Lasso (test)")
plot_confmat(cm_en,    main = "Elastic Net (test)")
par(mfrow = c(1,1))

# ---- OPTIONAL: If you want to tune alpha too (outer loop over alpha, inner CV for lambda) ----
# alphas <- c(0.1, 0.3, 0.5, 0.7, 0.9)
# set.seed(1)
# cv_list <- lapply(alphas, function(a) cv.glmnet(X_train, y_train, family="binomial", alpha=a, nfolds=k_folds))
# cv_mins <- sapply(cv_list, function(cv) min(cv$cvm))
# best_i <- which.min(cv_mins)
# best_alpha <- alphas[best_i]
# best_cv <- cv_list[[best_i]]
# cat("\nBest EN alpha by CV:", best_alpha, "\n")
# cat("Best EN lambda.min:", best_cv$lambda.min, "\n")
# plot(best_cv, main=paste0("Best EN CV (alpha=", best_alpha, ")"))
# abline(v=log(best_cv$lambda.min), lty=2)
# abline(v=log(best_cv$lambda.1se), lty=3)


# ROC Curves (Holdout Test Set)

# Create ROC objects (using test-set probabilities)
roc_ridge <- roc(y_test, prob_ridge, quiet = TRUE)
roc_lasso <- roc(y_test, prob_lasso, quiet = TRUE)
roc_en    <- roc(y_test, prob_en,    quiet = TRUE)

# Logistic may have failed; guard it
if (logit_ok && all(is.finite(prob_logit))) {
  roc_logit <- roc(y_test, prob_logit, quiet = TRUE)
}

# Plot
plot(roc_ridge, col = "blue",  lwd = 2,
     main = "ROC Curves (Holdout Test Set)")

lines(roc_lasso, col = "red",   lwd = 2)
lines(roc_en,    col = "darkgreen", lwd = 2)

if (exists("roc_logit")) {
  lines(roc_logit, col = "black", lwd = 2, lty = 2)
}

legend("bottomright",
       legend = c(
         paste0("Ridge (AUC=", round(auc(roc_ridge),3), ")"),
         paste0("Lasso (AUC=", round(auc(roc_lasso),3), ")"),
         paste0("EN (AUC=", round(auc(roc_en),3), ")"),
         if (exists("roc_logit"))
           paste0("Logistic (AUC=", round(auc(roc_logit),3), ")")
       ),
       col = c("blue","red","darkgreen","black"),
       lwd = 2,
       lty = c(1,1,1,2),
       bty = "n")
```


::: 

::: {.callout-tip collapse="true"}

### Example 3

Here I've used 1000 Genomes Project data as input for PCA. These data include "labels" for numerous ancestry groups.

Using my own 23andMe data, I projected PCs 1-3 for myself.

We can plot the PCs and see where I cluster.

Then, we apply k-NN to assign my sample to a population.

Note that hte `plotly` figures may not render in `webr`. You should be able copy, paste, and run this code in RStudio on your computer.

```{webr}
library(plotly)
library(data.table)
load(url("https://jmc108.github.io/hugen2073-textbook/exercises/11_machine_learning/example3.RData")) # ---- 3D PLOT ----
p <- plot_ly(
  ref_pcs,
  x = ~PC1, y = ~PC2, z = ~PC3,
  type = "scatter3d",
  mode = "markers",
  color = ~pop,
  text = ~paste0(sample, "<br>", pop, " (", pop, ")"),
  hoverinfo = "text",
  marker = list(size = 3)
)

p <- add_trace(
  p,
  x = c(jon_pc1), y = c(jon_pc2), z = c(jon_pc3),
  type = "scatter3d",
  mode = "markers",
  marker = list(size = 7, symbol = "diamond", color = "black"),
  text = "Jon",
  hoverinfo = "text",
  name = "Jon",
  inherit = FALSE
)

p


# ===================== KNN (pop + super_pop) on PCA coords + add Jon + plot with predicted color =====================
# Assumes you already have:
#   ref_pcs (data.frame with columns: sample, pop, super_pop, PC1, PC2, PC3)
#   jon_pc1, jon_pc2, jon_pc3 (numeric)
#   p (your existing plotly object created from ref_pcs; or you can recreate it below)

k_list <- c(3, 5, 7, 11, 21, 51)

# ---- helper: majority vote with tie-break by nearest-neighbor (distance) ----
knn_vote <- function(labels, dists) {
  tab <- sort(table(labels), decreasing = TRUE)
  top_n <- as.integer(tab[1])
  tied <- names(tab)[tab == top_n]
  if (length(tied) == 1) return(tied)
  # tie-break: among tied classes, pick the class of the single closest neighbor
  labels[which.min(dists)]
}

# ---- compute distances in 3D PC space ----
ref_mat <- as.matrix(ref_pcs[, c("PC1","PC2","PC3")])
jon_vec <- c(jon_pc1, jon_pc2, jon_pc3)
d <- sqrt(rowSums((ref_mat - matrix(jon_vec, nrow(ref_mat), 3, byrow = TRUE))^2))

ord <- order(d)

# ---- run KNN for multiple k and report ----
knn_results <- rbindlist(lapply(k_list, function(k) {
  idx <- ord[seq_len(k)]
  sp <- knn_vote(ref_pcs$super_pop[idx], d[idx])
  pp <- knn_vote(ref_pcs$pop[idx],       d[idx])
  data.table(k = k, pred_super_pop = sp, pred_pop = pp)
}))

print(knn_results)

# ---- pick a final k (majority among k's, tie-break by smallest k) ----
final_super <- names(sort(table(knn_results$pred_super_pop), decreasing = TRUE))[1]
final_pop   <- names(sort(table(knn_results$pred_pop),       decreasing = TRUE))[1]

cat("FINAL predicted super_pop:", final_super, "\n")
cat("FINAL predicted pop:      ", final_pop, "\n")

# ---- add Jon to ref_pcs with predicted labels (so he shares the SAME color mapping) ----
jon_row <- data.frame(
  sample = "Jon",
  pop = final_pop,
  super_pop = final_super,
  PC1 = jon_pc1, PC2 = jon_pc2, PC3 = jon_pc3,
  stringsAsFactors = FALSE
)

ref_plus_jon <- rbind(ref_pcs, jon_row)

# ---- plot: keep reference colored by super_pop; add Jon as same color (mapped) but unique symbol ----
p2 <- plot_ly(
  ref_plus_jon,
  x = ~PC1, y = ~PC2, z = ~PC3,
  type = "scatter3d",
  mode = "markers",
  color = ~pop,
  text = ~paste0(sample, "<br>", pop, " (", pop, ")"),
  hoverinfo = "text",
  marker = list(size = 3),
  showlegend = TRUE
)

# add Jon as separate trace so we can force the unique symbol/size, but keep color consistent:
jon_color <- unique(ref_plus_jon$super_pop[ref_plus_jon$sample == "Jon"])
# plotly won't let us directly "inherit" the exact palette color reliably without reusing the same mapping;
# easiest is: add Jon as a filtered trace that still maps color by super_pop, then override symbol/size
p2 <- add_trace(
  p2,
  data = subset(ref_plus_jon, sample == "Jon"),
  x = ~PC1, y = ~PC2, z = ~PC3,
  type = "scatter3d",
  mode = "markers",
  color = ~pop,                 # <-- keeps same color mapping
  marker = list(size = 8, symbol = "diamond", line = list(width = 1)),
  text = ~paste0("Jon<br>", pop, " (", pop, ")"),
  hoverinfo = "text",
  name = "Jon",
  inherit = FALSE,
  showlegend = FALSE
)

p2


p3 <-
  ggplot() +
  # Reference samples
  geom_point(
    data = subset(ref_plus_jon, sample != "Jon"),
    aes(
      x = PC1,
      y = PC2,
      color = pop,
      text = paste0(
        "Sample: ", sample,
        "<br>Pop: ", pop,
        "<br>SuperPop: ", super_pop
      )
    ),
    size = 2,
    alpha = 0.7
  ) +
  # Jon on top
  geom_point(
    data = subset(ref_plus_jon, sample == "Jon"),
    aes(
      x = PC1,
      y = PC2,
      text = paste0(
        "Sample: Jon",
        "<br>Predicted Pop: ", pop,
        "<br>Predicted SuperPop: ", super_pop
      )
    ),
    size = 4,
    shape = 18,
    color = "black"
  )

# Convert to interactive
ggplotly(p3, tooltip = "text")


# ===================== end KNN block =====================

```


::: 